// <auto-generated />
using System;
using DevHunter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevHunter.Data.Migrations
{
    [DbContext(typeof(DevHunterDbContext))]
    [Migration("20240402184122_FixTechnologyAndDevelopmentConfiguration")]
    partial class FixTechnologyAndDevelopmentConfiguration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DevHunter.Data.Models.ApplicationDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("ApplicationDocuments");
                });

            modelBuilder.Entity("DevHunter.Data.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DevHunter.Data.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FoundedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("DevHunter.Data.Models.CompanyTechnologies", b =>
                {
                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CompanyId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("CompanyTechnologies");
                });

            modelBuilder.Entity("DevHunter.Data.Models.Development", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Developments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4423b2a0-4b46-49fd-b6cd-92eadfcbcfd0"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1711954697/DevHunter/development/Backend%20Development.png",
                            Name = "Backend Development"
                        },
                        new
                        {
                            Id = new Guid("c385035d-2a4d-442a-b6ca-6443bb378be1"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1711959225/DevHunter/development/Frontend%20Development.png",
                            Name = "Frontend Development"
                        },
                        new
                        {
                            Id = new Guid("010164b3-025f-461c-b393-b35bd679bf30"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052843/DevHunter/development/Customer%20Support.png",
                            Name = "Customer Support"
                        },
                        new
                        {
                            Id = new Guid("58e9c362-031c-4106-a273-7b730162f23b"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052406/DevHunter/development/Fullstack%20Development.png",
                            Name = "Fullstack Development"
                        },
                        new
                        {
                            Id = new Guid("f86ea64b-6602-48e6-a951-c4eed172decd"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052843/DevHunter/development/Data%20Science.png",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = new Guid("6c5ab4bf-2e97-4c27-8483-bbbdb4a6aad7"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052843/DevHunter/development/Hardware%20and%20Engineering.png",
                            Name = "Hardware and Engineering"
                        },
                        new
                        {
                            Id = new Guid("5f4e14ae-b693-4f22-8167-4c808c436391"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052844/DevHunter/development/IT%20Management.png",
                            Name = "IT Management"
                        },
                        new
                        {
                            Id = new Guid("8b1cdd7b-2455-4067-96f0-452a7a9eba50"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052843/DevHunter/development/ERP%20-%20CRM%20development.png",
                            Name = "ERP / CRM Development"
                        },
                        new
                        {
                            Id = new Guid("134cb2eb-71a2-430f-ae7d-b01895cbefb8"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052844/DevHunter/development/Infrastructure.png",
                            Name = "Infrastructure"
                        },
                        new
                        {
                            Id = new Guid("60151c1f-394a-49e4-8777-fd85d41f1341"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052844/DevHunter/development/Junior%20-%20Intern.png",
                            Name = "Junior/Intern"
                        },
                        new
                        {
                            Id = new Guid("09b3a04b-ca29-42db-8f68-85e92f8c83ac"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052844/DevHunter/development/Mobile%20Development.png",
                            Name = "Mobile Development"
                        },
                        new
                        {
                            Id = new Guid("3925bab7-3529-47e6-807f-37a57d9c9cfd"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052844/DevHunter/development/PM%20-%20BA%20and%20more.png",
                            Name = "PM/BA and more"
                        },
                        new
                        {
                            Id = new Guid("8448cd52-5cb6-4a42-8324-17c34e58837f"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052845/DevHunter/development/Quality%20Assurance.png",
                            Name = "Quality Assurance"
                        },
                        new
                        {
                            Id = new Guid("5223d4e3-3508-47ca-a24c-538923500838"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052845/DevHunter/development/Technical%20Support.png",
                            Name = "Technical Support"
                        },
                        new
                        {
                            Id = new Guid("49bbc31e-0241-411e-81c2-3356d002d3d6"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712052845/DevHunter/development/UI%20-%20UX%2C%20Arts.png",
                            Name = "UI/UX, Arts"
                        });
                });

            modelBuilder.Entity("DevHunter.Data.Models.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CandidateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MotivationalLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobOfferId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("DevHunter.Data.Models.JobOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobPlace")
                        .HasColumnType("int");

                    b.Property<string>("JobPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlaceToWork")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkingHours")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("JobOffers");
                });

            modelBuilder.Entity("DevHunter.Data.Models.SavedJobOffer", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "JobOfferId");

                    b.HasIndex("JobOfferId");

                    b.ToTable("SavedJobOffers");
                });

            modelBuilder.Entity("DevHunter.Data.Models.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb8aafc8-0ac4-4694-9dda-a10ddfdd31ce"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071533/DevHunter/technology/Go.png",
                            Name = "Go"
                        },
                        new
                        {
                            Id = new Guid("62b07f73-52ce-44c1-8e19-91bac46a6074"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709496382/DevHunter/technology/HTML5.png",
                            Name = "Html5"
                        },
                        new
                        {
                            Id = new Guid("1194737c-bef9-4091-a36c-6dc1c8f574e9"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709495915/DevHunter/technology/Kubernetes.png",
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = new Guid("c43707a9-9307-476c-95e6-3c1381364e0e"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709496039/DevHunter/technology/Apache.png",
                            Name = "Apache"
                        },
                        new
                        {
                            Id = new Guid("9dcfddda-5de8-4406-8e73-c4c0f6f0951e"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709496307/DevHunter/technology/Angular.png",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = new Guid("56e3673e-0798-4f06-b348-d6129e385bad"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709495970/DevHunter/technology/Javascript.png",
                            Name = "Javascript"
                        },
                        new
                        {
                            Id = new Guid("88ce0fe5-bd18-4d14-97bd-0bceb7213ab4"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709496353/DevHunter/technology/Gitlab.jpg",
                            Name = "Gitlab"
                        },
                        new
                        {
                            Id = new Guid("cc431206-48a9-42f7-816b-1c720977a2ea"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709495888/DevHunter/technology/CSS.png",
                            Name = "CSS"
                        },
                        new
                        {
                            Id = new Guid("361f8fcb-ca22-459a-94c1-3f9e7b3faa25"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709495873/DevHunter/technology/Bootstrap.png",
                            Name = "Bootstrap"
                        },
                        new
                        {
                            Id = new Guid("8b8d6dc4-5abe-46fe-b7f9-dbe2c5d2fac9"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709495988/DevHunter/technology/React.png",
                            Name = "React"
                        },
                        new
                        {
                            Id = new Guid("b540d04c-7569-493e-a390-62f3df559d4f"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709496410/DevHunter/technology/Python.png",
                            Name = "Python"
                        },
                        new
                        {
                            Id = new Guid("57c726d8-8348-4c10-b039-610c7c95c21c"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709495978/DevHunter/technology/Django.png",
                            Name = "Django"
                        },
                        new
                        {
                            Id = new Guid("382e7a27-67cd-4ff0-8f2e-f81051798905"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709496008/DevHunter/technology/MongoDb.png",
                            Name = "MongoDb"
                        },
                        new
                        {
                            Id = new Guid("3a94c0b2-5737-49c9-82a0-2b981ca2aed8"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709496318/DevHunter/technology/Ansible.png",
                            Name = "Ansible"
                        },
                        new
                        {
                            Id = new Guid("c2f40ecc-4f66-4e5b-92fd-7a7bf898bb10"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709496362/DevHunter/technology/Flink.png",
                            Name = "Flink"
                        },
                        new
                        {
                            Id = new Guid("9716bf74-9616-4fcc-a33a-3b3801a89ae1"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709496341/DevHunter/technology/Ecma.png",
                            Name = "Ecma"
                        },
                        new
                        {
                            Id = new Guid("29704a55-8dff-46d3-ad94-6fca2a393b48"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709495925/DevHunter/technology/Linux.png",
                            Name = "Linux"
                        },
                        new
                        {
                            Id = new Guid("85eb8c55-d4ac-4408-8167-8887f9b3dc78"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709496395/DevHunter/technology/Typescript.png",
                            Name = "Typescript"
                        },
                        new
                        {
                            Id = new Guid("de1b71b5-0646-4740-bda8-70334f459601"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709495940/DevHunter/technology/MariaDb.png",
                            Name = "MariaDb"
                        },
                        new
                        {
                            Id = new Guid("4972cc43-375b-40a7-829d-9c0acaefbcf0"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709495957/DevHunter/technology/Nodejs.png",
                            Name = "Nodejs"
                        },
                        new
                        {
                            Id = new Guid("b06f66e5-1531-4343-8a88-2ffa4b981bcc"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709495897/DevHunter/technology/Docker.jpg",
                            Name = "Docker"
                        },
                        new
                        {
                            Id = new Guid("e6218084-2b54-4165-b8a9-60c0d9ee7e1d"),
                            ImageUrl = "http://res.cloudinary.com/dlffxtrek/image/upload/v1709496838/DevHunter/technology/Vue.png",
                            Name = "Vue"
                        },
                        new
                        {
                            Id = new Guid("f66c9fc1-f609-4049-a8e4-cd01b152315e"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1710397054/DevHunter/technology/English.png",
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("78cefe08-c625-4bda-bbd8-67c1cf91c1fa"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1710397175/DevHunter/technology/Kotlin.png",
                            Name = "Kotlin"
                        },
                        new
                        {
                            Id = new Guid("055f5e0a-ea4f-4335-a37c-ec829fe0b395"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1710397259/DevHunter/technology/Npm.png",
                            Name = "Npm"
                        },
                        new
                        {
                            Id = new Guid("fd19139b-6abf-4d8d-99fc-2f35213c750c"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1710415630/DevHunter/technology/Json.png",
                            Name = "Json"
                        },
                        new
                        {
                            Id = new Guid("c7296f6a-2f8b-42d8-9cc3-7bd6111c576a"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1710665563/DevHunter/technology/Cypress.jpg",
                            Name = "Cypress"
                        },
                        new
                        {
                            Id = new Guid("fb31126c-96f7-4043-abaf-009ac7942537"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1710849528/DevHunter/technology/Elastic%20searh.png",
                            Name = "Elastic search"
                        },
                        new
                        {
                            Id = new Guid("5c55f4b2-7f9b-434b-9478-fae3c846f900"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1710850042/DevHunter/technology/AWS.png",
                            Name = "AWS"
                        },
                        new
                        {
                            Id = new Guid("1e6ff7c4-ac00-4738-b124-9608b126e979"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1710850648/DevHunter/technology/Jest.jpg",
                            Name = "Jest"
                        },
                        new
                        {
                            Id = new Guid("dd012c57-87fa-421b-a955-75a7504b7794"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1711954963/DevHunter/technology/Spring.png",
                            Name = "Spring"
                        },
                        new
                        {
                            Id = new Guid("e702256c-0504-41e2-aa0d-65c3bffa1095"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071517/DevHunter/technology/ilustrator.png",
                            Name = "Adobe Illustrator"
                        },
                        new
                        {
                            Id = new Guid("4fae2df2-174d-43a3-b6d7-a46eb1b298ec"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071517/DevHunter/technology/Adobe%20Creative.png",
                            Name = "Adobe Creative"
                        },
                        new
                        {
                            Id = new Guid("8a8e4999-65b7-4c87-92de-be929ac0169f"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071518/DevHunter/technology/Xd.png",
                            Name = "Adobe Xd"
                        },
                        new
                        {
                            Id = new Guid("96ff8fde-ca05-47f6-8dd9-1bb9db0f58b8"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071518/DevHunter/technology/Adobe.png",
                            Name = "Adobe"
                        },
                        new
                        {
                            Id = new Guid("4d77692e-1582-4bd5-b3b9-dc8fa496c690"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071519/DevHunter/technology/Apache%20Apex.png",
                            Name = "Apache Apex"
                        },
                        new
                        {
                            Id = new Guid("df7e83ee-76f9-4ef0-97fe-930e79230c20"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071520/DevHunter/technology/Argo%20CD.png",
                            Name = "Argo CD"
                        },
                        new
                        {
                            Id = new Guid("dbd65e30-7822-429c-9217-9f53adcc8060"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071520/DevHunter/technology/Photoshop.png",
                            Name = "Adobe Photoshop"
                        },
                        new
                        {
                            Id = new Guid("48ba2840-ceb6-4546-9d03-9b9163b131d5"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071520/DevHunter/technology/ASP.Net.png",
                            Name = "ASP.Net"
                        },
                        new
                        {
                            Id = new Guid("a111ea4f-b5e1-404a-98f4-29703b584333"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071520/DevHunter/technology/AWAF.png",
                            Name = "AWAF"
                        },
                        new
                        {
                            Id = new Guid("e6ded6a5-8674-490f-aa6c-50f2eb477132"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071521/DevHunter/technology/AWS%20Cloudformation.png",
                            Name = "AWS Cloudformation"
                        },
                        new
                        {
                            Id = new Guid("40e8906f-241b-4b60-b957-9e64b1c1e7a7"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071521/DevHunter/technology/Azure.png",
                            Name = "Azure"
                        },
                        new
                        {
                            Id = new Guid("55cee988-b391-4796-8ba2-f7bc132d98c6"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071522/DevHunter/technology/Babel.png",
                            Name = "Babel"
                        },
                        new
                        {
                            Id = new Guid("9d4a5af6-3409-45f7-a326-7b8f769fe764"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071522/DevHunter/technology/Balsamia.png",
                            Name = "Balsamia"
                        },
                        new
                        {
                            Id = new Guid("e365f0cc-e847-482f-9cd2-3bc87df71ecb"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071522/DevHunter/technology/Bitbucket.png",
                            Name = "Bitbucket"
                        },
                        new
                        {
                            Id = new Guid("7efbded2-e248-46d5-b460-ae908229cb2c"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071523/DevHunter/technology/Blockchain.png",
                            Name = "Blockchain"
                        },
                        new
                        {
                            Id = new Guid("f17cd3dd-0853-4a47-95bb-7449128c7fda"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071524/DevHunter/technology/C.jpg",
                            Name = "C++"
                        },
                        new
                        {
                            Id = new Guid("f1aaf947-ccbf-4418-a55a-7c48931cb4bf"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071524/DevHunter/technology/Confluence.png",
                            Name = "Confluence"
                        },
                        new
                        {
                            Id = new Guid("7b61c994-30e7-48b0-b8a7-2377763627ea"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071525/DevHunter/technology/Coredraw.jpg",
                            Name = "Coredraw"
                        },
                        new
                        {
                            Id = new Guid("64ff7067-eb71-49d1-8672-ac5d71da71ac"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071525/DevHunter/technology/Csharp.png",
                            Name = "C#"
                        },
                        new
                        {
                            Id = new Guid("47656ee3-b8dd-417f-9116-9f6569f67787"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071526/DevHunter/technology/Davinci%20Resolve.png",
                            Name = "Davinci Resolve"
                        },
                        new
                        {
                            Id = new Guid("ff98cf9c-d2be-409a-93a3-306ff8c3aacc"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071527/DevHunter/technology/DNS.png",
                            Name = "DNS"
                        },
                        new
                        {
                            Id = new Guid("b46807cb-75fa-4039-80f2-df044be56f90"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071528/DevHunter/technology/Dragonbones.png",
                            Name = "Dragon bones"
                        },
                        new
                        {
                            Id = new Guid("fcbf7357-7271-497e-a76f-6bf3f27178e4"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071528/DevHunter/technology/Drawio.png",
                            Name = "Draw.io"
                        },
                        new
                        {
                            Id = new Guid("773fa43e-1d6e-41c2-a029-c0e15773e565"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071529/DevHunter/technology/Event%20bridge.jpg",
                            Name = "Event bridge"
                        },
                        new
                        {
                            Id = new Guid("2c1b6d09-a0ce-4247-827d-8ac66f0d3bf4"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071530/DevHunter/technology/Excel.png",
                            Name = "Excel"
                        },
                        new
                        {
                            Id = new Guid("74638738-681d-4375-95a7-3c9016b68383"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071530/DevHunter/technology/Figma.png",
                            Name = "Figma"
                        },
                        new
                        {
                            Id = new Guid("1c30015e-939d-4104-82d9-eeed2eca6210"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071530/DevHunter/technology/Firewall.png",
                            Name = "Firewall"
                        },
                        new
                        {
                            Id = new Guid("218f872d-55e4-4bb4-8252-41a667dcd39c"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071531/DevHunter/technology/French.png",
                            Name = "French"
                        },
                        new
                        {
                            Id = new Guid("593da6d6-919f-457f-b726-5889aa0caab9"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071531/DevHunter/technology/German.png",
                            Name = "German"
                        },
                        new
                        {
                            Id = new Guid("097d02e0-0577-4110-8fb7-8989f60d53b9"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071532/DevHunter/technology/Git.png",
                            Name = "Git"
                        },
                        new
                        {
                            Id = new Guid("09bead07-5680-4204-a837-2bf34509b3af"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071532/DevHunter/technology/Github.png",
                            Name = "Github"
                        },
                        new
                        {
                            Id = new Guid("8f655fe5-67cb-4a15-98d0-579bf136c31d"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071533/DevHunter/technology/Google%20cloud.png",
                            Name = "Google Creative"
                        },
                        new
                        {
                            Id = new Guid("a664a739-89bc-4b37-a343-402c4ab5b198"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071534/DevHunter/technology/Graphql.png",
                            Name = "Graphql"
                        },
                        new
                        {
                            Id = new Guid("646b656f-3fb9-47d5-80e4-ba0f807e70d3"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071534/DevHunter/technology/Informatica.png",
                            Name = "Informatica"
                        },
                        new
                        {
                            Id = new Guid("88a342ad-594b-4fff-91ee-ce21baadf092"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071535/DevHunter/technology/Internet%20of%20things.png",
                            Name = "Internet of things"
                        },
                        new
                        {
                            Id = new Guid("4815599e-4d99-458a-ad41-de90b75b3c0f"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071535/DevHunter/technology/iOs.png",
                            Name = "iOS"
                        },
                        new
                        {
                            Id = new Guid("ad4ee1df-2cc4-48d1-9914-bbd68df162ff"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071535/DevHunter/technology/IP.png",
                            Name = "IP"
                        },
                        new
                        {
                            Id = new Guid("85d93d19-68e5-4baa-8d91-72cd70a6fcea"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071536/DevHunter/technology/Java.png",
                            Name = "Java"
                        },
                        new
                        {
                            Id = new Guid("e1fdc176-5f0e-44a2-8b02-84f757fe5118"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071536/DevHunter/technology/Jenkins.png",
                            Name = "Jenkins"
                        },
                        new
                        {
                            Id = new Guid("2961db2f-88a5-4831-b721-ebf69eff0e2b"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071537/DevHunter/technology/Jira.png",
                            Name = "Jira"
                        },
                        new
                        {
                            Id = new Guid("0b05da1d-b9ae-42e2-a86e-b3746674e6cd"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071537/DevHunter/technology/jQuery.png",
                            Name = "jQuery"
                        },
                        new
                        {
                            Id = new Guid("564bb8e0-14f2-4812-a754-18697abd6bd7"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071538/DevHunter/technology/Kicad.png",
                            Name = "Kicad"
                        },
                        new
                        {
                            Id = new Guid("a8dfa119-36fe-4b45-a8a1-017289b4eea5"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071539/DevHunter/technology/Mac%20OS.png",
                            Name = "Mac OS"
                        },
                        new
                        {
                            Id = new Guid("81692dbb-1b59-432b-a2fa-a56115b38e77"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071540/DevHunter/technology/Microsoft%20office.png",
                            Name = "Microsoft office"
                        },
                        new
                        {
                            Id = new Guid("51a1d7d5-2eb9-4b82-b161-c5663ac52e90"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071540/DevHunter/technology/Maven.png",
                            Name = "Maven"
                        },
                        new
                        {
                            Id = new Guid("a4adde33-5e29-4520-b703-625195b17adc"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071541/DevHunter/technology/Mysql.png",
                            Name = "Mysql"
                        },
                        new
                        {
                            Id = new Guid("7397e5d6-527e-47f9-8f23-20dd62692500"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071542/DevHunter/technology/Net.png",
                            Name = ".Net"
                        },
                        new
                        {
                            Id = new Guid("5cd0472e-8077-4893-890e-b4bb953c0885"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071542/DevHunter/technology/NetCore.png",
                            Name = ".Net Core"
                        },
                        new
                        {
                            Id = new Guid("2a698b89-b775-41f4-b97d-f20942a72b8d"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071543/DevHunter/technology/Oracle.png",
                            Name = "Oracle"
                        },
                        new
                        {
                            Id = new Guid("b21cc378-8485-4de2-b282-ff63aee397bd"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071543/DevHunter/technology/Outlook.png",
                            Name = "Microsoft Outlook"
                        },
                        new
                        {
                            Id = new Guid("0c07e73e-21de-4d34-acf8-15f1ed993ee9"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071544/DevHunter/technology/Php.jpg",
                            Name = "PHP"
                        },
                        new
                        {
                            Id = new Guid("32bd6276-3776-40a9-a278-73d6dbfed488"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071544/DevHunter/technology/Playright.png",
                            Name = "Playright"
                        },
                        new
                        {
                            Id = new Guid("39a790cb-1cc9-4fc8-b1c3-ad957bfb28af"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071544/DevHunter/technology/Postgresql.png",
                            Name = "Postgresql"
                        },
                        new
                        {
                            Id = new Guid("049faadc-8d63-4cda-af30-3a8dc6a17ef1"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071545/DevHunter/technology/Postman.png",
                            Name = "Postman"
                        },
                        new
                        {
                            Id = new Guid("a367010c-a083-490c-b2ed-976ee8f49c53"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071545/DevHunter/technology/Powershell.png",
                            Name = "Powershell"
                        },
                        new
                        {
                            Id = new Guid("97d7e08e-f34d-4105-9508-133bcde2c403"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071546/DevHunter/technology/RDBMS.png",
                            Name = "RDBMS"
                        },
                        new
                        {
                            Id = new Guid("075ec4e5-5197-456c-9a75-aa215fa8b3da"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071546/DevHunter/technology/Ruby.png",
                            Name = "Ruby"
                        },
                        new
                        {
                            Id = new Guid("1e27c97f-ffdb-4d3a-afc6-6d4d75532711"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071547/DevHunter/technology/Salesforce.png",
                            Name = "Salesforce"
                        },
                        new
                        {
                            Id = new Guid("e0988db1-54b6-47b9-9293-c96423280230"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071547/DevHunter/technology/SAS.png",
                            Name = "SAS"
                        },
                        new
                        {
                            Id = new Guid("ed1f9d3f-835c-4af3-95a1-fa2f32e67f4e"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071547/DevHunter/technology/Selenium.png",
                            Name = "Selenium"
                        },
                        new
                        {
                            Id = new Guid("2250faa8-6a00-40cc-8bfc-ac6f04601d79"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071548/DevHunter/technology/Shellbash.png",
                            Name = "Shellbash"
                        },
                        new
                        {
                            Id = new Guid("7a199941-2479-425a-9d3b-f7a73ad05c7f"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071548/DevHunter/technology/Shopify.png",
                            Name = "Shopify"
                        },
                        new
                        {
                            Id = new Guid("34e4a9b0-deb3-4479-939c-1f37a354c155"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071548/DevHunter/technology/Sketch.png",
                            Name = "Sketch"
                        },
                        new
                        {
                            Id = new Guid("1835a5be-934c-4149-a7bf-72e4d22589b0"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071549/DevHunter/technology/Spine.png",
                            Name = "Spine"
                        },
                        new
                        {
                            Id = new Guid("ac85a8f7-8055-431e-a343-96126fcd4680"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071549/DevHunter/technology/SQL.png",
                            Name = "SQL"
                        },
                        new
                        {
                            Id = new Guid("c3fe8667-8b40-4057-bcd6-cba4e5c17370"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071550/DevHunter/technology/Tailwind%20CSS.jpg",
                            Name = "Tailwind CSS"
                        },
                        new
                        {
                            Id = new Guid("f7861a1b-f927-475f-9a9c-86aa1e923b73"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071550/DevHunter/technology/Terraform.png",
                            Name = "Terraform"
                        },
                        new
                        {
                            Id = new Guid("6485e41d-f52a-43a8-821c-cc18498406d2"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071551/DevHunter/technology/Visio.png",
                            Name = "Visio"
                        },
                        new
                        {
                            Id = new Guid("329bd2e3-a970-4ce0-be03-bc5e5e568d2d"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071551/DevHunter/technology/Visual%20studio.png",
                            Name = "Visual Studio"
                        },
                        new
                        {
                            Id = new Guid("a2b5056f-bea7-4a9b-b2f7-322cef5ba16b"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071552/DevHunter/technology/Waterfall.jpg",
                            Name = "Waterfall"
                        },
                        new
                        {
                            Id = new Guid("68153bf6-f21f-4029-add0-95575725afed"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071552/DevHunter/technology/Windows.png",
                            Name = "Windows"
                        },
                        new
                        {
                            Id = new Guid("fe4648c2-8e4f-42b1-b27b-d5826830e76a"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712071553/DevHunter/technology/Wordpress.png",
                            Name = "Wordpress"
                        },
                        new
                        {
                            Id = new Guid("d9fa804a-d7dd-4ba4-b790-8827a6b06e1e"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712077397/DevHunter/technology/NUnit.png",
                            Name = "NUnit"
                        },
                        new
                        {
                            Id = new Guid("8c8373a3-a9bf-4b31-96d8-e9a8ec6a5f13"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712078787/DevHunter/technology/SAP.png",
                            Name = "SAP"
                        },
                        new
                        {
                            Id = new Guid("6208abee-b855-4281-beaa-aa94673784a0"),
                            ImageUrl = "https://res.cloudinary.com/dlffxtrek/image/upload/v1712078890/DevHunter/technology/Android.png",
                            Name = "Android"
                        });
                });

            modelBuilder.Entity("DevHunter.Data.Models.TechnologyDevelopments", b =>
                {
                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DevelopmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("TechnologyId", "DevelopmentId");

                    b.HasIndex("DevelopmentId");

                    b.ToTable("TechnologiesDevelopments");

                    b.HasData(
                        new
                        {
                            TechnologyId = new Guid("7397e5d6-527e-47f9-8f23-20dd62692500"),
                            DevelopmentId = new Guid("4423b2a0-4b46-49fd-b6cd-92eadfcbcfd0"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("85d93d19-68e5-4baa-8d91-72cd70a6fcea"),
                            DevelopmentId = new Guid("4423b2a0-4b46-49fd-b6cd-92eadfcbcfd0"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("85eb8c55-d4ac-4408-8167-8887f9b3dc78"),
                            DevelopmentId = new Guid("4423b2a0-4b46-49fd-b6cd-92eadfcbcfd0"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("64ff7067-eb71-49d1-8672-ac5d71da71ac"),
                            DevelopmentId = new Guid("4423b2a0-4b46-49fd-b6cd-92eadfcbcfd0"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("075ec4e5-5197-456c-9a75-aa215fa8b3da"),
                            DevelopmentId = new Guid("4423b2a0-4b46-49fd-b6cd-92eadfcbcfd0"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("b540d04c-7569-493e-a390-62f3df559d4f"),
                            DevelopmentId = new Guid("4423b2a0-4b46-49fd-b6cd-92eadfcbcfd0"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("bb8aafc8-0ac4-4694-9dda-a10ddfdd31ce"),
                            DevelopmentId = new Guid("4423b2a0-4b46-49fd-b6cd-92eadfcbcfd0"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("4972cc43-375b-40a7-829d-9c0acaefbcf0"),
                            DevelopmentId = new Guid("4423b2a0-4b46-49fd-b6cd-92eadfcbcfd0"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("56e3673e-0798-4f06-b348-d6129e385bad"),
                            DevelopmentId = new Guid("c385035d-2a4d-442a-b6ca-6443bb378be1"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("8b8d6dc4-5abe-46fe-b7f9-dbe2c5d2fac9"),
                            DevelopmentId = new Guid("c385035d-2a4d-442a-b6ca-6443bb378be1"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("9dcfddda-5de8-4406-8e73-c4c0f6f0951e"),
                            DevelopmentId = new Guid("c385035d-2a4d-442a-b6ca-6443bb378be1"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("e6218084-2b54-4165-b8a9-60c0d9ee7e1d"),
                            DevelopmentId = new Guid("c385035d-2a4d-442a-b6ca-6443bb378be1"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("1194737c-bef9-4091-a36c-6dc1c8f574e9"),
                            DevelopmentId = new Guid("134cb2eb-71a2-430f-ae7d-b01895cbefb8"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("a367010c-a083-490c-b2ed-976ee8f49c53"),
                            DevelopmentId = new Guid("134cb2eb-71a2-430f-ae7d-b01895cbefb8"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("f7861a1b-f927-475f-9a9c-86aa1e923b73"),
                            DevelopmentId = new Guid("134cb2eb-71a2-430f-ae7d-b01895cbefb8"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("e1fdc176-5f0e-44a2-8b02-84f757fe5118"),
                            DevelopmentId = new Guid("134cb2eb-71a2-430f-ae7d-b01895cbefb8"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("d9fa804a-d7dd-4ba4-b790-8827a6b06e1e"),
                            DevelopmentId = new Guid("8448cd52-5cb6-4a42-8324-17c34e58837f"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("ed1f9d3f-835c-4af3-95a1-fa2f32e67f4e"),
                            DevelopmentId = new Guid("8448cd52-5cb6-4a42-8324-17c34e58837f"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("88a342ad-594b-4fff-91ee-ce21baadf092"),
                            DevelopmentId = new Guid("3925bab7-3529-47e6-807f-37a57d9c9cfd"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("81692dbb-1b59-432b-a2fa-a56115b38e77"),
                            DevelopmentId = new Guid("3925bab7-3529-47e6-807f-37a57d9c9cfd"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("646b656f-3fb9-47d5-80e4-ba0f807e70d3"),
                            DevelopmentId = new Guid("3925bab7-3529-47e6-807f-37a57d9c9cfd"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("2961db2f-88a5-4831-b721-ebf69eff0e2b"),
                            DevelopmentId = new Guid("3925bab7-3529-47e6-807f-37a57d9c9cfd"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("f1aaf947-ccbf-4418-a55a-7c48931cb4bf"),
                            DevelopmentId = new Guid("3925bab7-3529-47e6-807f-37a57d9c9cfd"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("e0988db1-54b6-47b9-9293-c96423280230"),
                            DevelopmentId = new Guid("f86ea64b-6602-48e6-a951-c4eed172decd"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("c43707a9-9307-476c-95e6-3c1381364e0e"),
                            DevelopmentId = new Guid("f86ea64b-6602-48e6-a951-c4eed172decd"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("2a698b89-b775-41f4-b97d-f20942a72b8d"),
                            DevelopmentId = new Guid("f86ea64b-6602-48e6-a951-c4eed172decd"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("1835a5be-934c-4149-a7bf-72e4d22589b0"),
                            DevelopmentId = new Guid("f86ea64b-6602-48e6-a951-c4eed172decd"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("1e27c97f-ffdb-4d3a-afc6-6d4d75532711"),
                            DevelopmentId = new Guid("8b1cdd7b-2455-4067-96f0-452a7a9eba50"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("8c8373a3-a9bf-4b31-96d8-e9a8ec6a5f13"),
                            DevelopmentId = new Guid("8b1cdd7b-2455-4067-96f0-452a7a9eba50"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("4815599e-4d99-458a-ad41-de90b75b3c0f"),
                            DevelopmentId = new Guid("09b3a04b-ca29-42db-8f68-85e92f8c83ac"),
                            IsActive = true
                        },
                        new
                        {
                            TechnologyId = new Guid("6208abee-b855-4281-beaa-aa94673784a0"),
                            DevelopmentId = new Guid("09b3a04b-ca29-42db-8f68-85e92f8c83ac"),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("DevHunter.Data.Models.TechnologyJobOffers", b =>
                {
                    b.Property<Guid>("JobOfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("JobOfferId", "TechnologyId");

                    b.HasIndex("TechnologyId");

                    b.ToTable("TechnologyJobOffers");
                });

            modelBuilder.Entity("DevHunter.Data.Models.UserJobApplications", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("JobApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "JobApplicationId");

                    b.HasIndex("JobApplicationId");

                    b.ToTable("UsersJobApplications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DevHunter.Data.Models.ApplicationDocument", b =>
                {
                    b.HasOne("DevHunter.Data.Models.JobApplication", "JobApplication")
                        .WithMany("Documents")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");
                });

            modelBuilder.Entity("DevHunter.Data.Models.Company", b =>
                {
                    b.HasOne("DevHunter.Data.Models.ApplicationUser", "Creator")
                        .WithMany("Companies")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("DevHunter.Data.Models.CompanyTechnologies", b =>
                {
                    b.HasOne("DevHunter.Data.Models.Company", "Company")
                        .WithMany("UsedTechnologies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHunter.Data.Models.Technology", "Technology")
                        .WithMany("CompanyTechnologies")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("DevHunter.Data.Models.JobApplication", b =>
                {
                    b.HasOne("DevHunter.Data.Models.JobOffer", "JobOffer")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOffer");
                });

            modelBuilder.Entity("DevHunter.Data.Models.JobOffer", b =>
                {
                    b.HasOne("DevHunter.Data.Models.Company", "Company")
                        .WithMany("JobOffers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("DevHunter.Data.Models.SavedJobOffer", b =>
                {
                    b.HasOne("DevHunter.Data.Models.JobOffer", "JobOffer")
                        .WithMany("SavedJobOffers")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHunter.Data.Models.ApplicationUser", "User")
                        .WithMany("SavedJobOffers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOffer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevHunter.Data.Models.TechnologyDevelopments", b =>
                {
                    b.HasOne("DevHunter.Data.Models.Development", "Development")
                        .WithMany("DevelopmentTechnologies")
                        .HasForeignKey("DevelopmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHunter.Data.Models.Technology", "Technology")
                        .WithMany("TechnologyDevelopments")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Development");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("DevHunter.Data.Models.TechnologyJobOffers", b =>
                {
                    b.HasOne("DevHunter.Data.Models.JobOffer", "JobOffer")
                        .WithMany("JobOfferTechnologies")
                        .HasForeignKey("JobOfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHunter.Data.Models.Technology", "Technology")
                        .WithMany("TechnologyJobOffers")
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobOffer");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("DevHunter.Data.Models.UserJobApplications", b =>
                {
                    b.HasOne("DevHunter.Data.Models.JobApplication", "JobApplication")
                        .WithMany("UserJobApplications")
                        .HasForeignKey("JobApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHunter.Data.Models.ApplicationUser", "User")
                        .WithMany("JobApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobApplication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DevHunter.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DevHunter.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevHunter.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DevHunter.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevHunter.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("JobApplications");

                    b.Navigation("SavedJobOffers");
                });

            modelBuilder.Entity("DevHunter.Data.Models.Company", b =>
                {
                    b.Navigation("JobOffers");

                    b.Navigation("UsedTechnologies");
                });

            modelBuilder.Entity("DevHunter.Data.Models.Development", b =>
                {
                    b.Navigation("DevelopmentTechnologies");
                });

            modelBuilder.Entity("DevHunter.Data.Models.JobApplication", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("UserJobApplications");
                });

            modelBuilder.Entity("DevHunter.Data.Models.JobOffer", b =>
                {
                    b.Navigation("JobApplications");

                    b.Navigation("JobOfferTechnologies");

                    b.Navigation("SavedJobOffers");
                });

            modelBuilder.Entity("DevHunter.Data.Models.Technology", b =>
                {
                    b.Navigation("CompanyTechnologies");

                    b.Navigation("TechnologyDevelopments");

                    b.Navigation("TechnologyJobOffers");
                });
#pragma warning restore 612, 618
        }
    }
}
