name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore ./src/DevHunter.Web/DevHunter.Web.csproj
    - name: Build
      run: dotnet build ./src/DevHunter.Web/
    - name: Test with the dotnet CLI
      run: dotnet test ./src/DevHunter.Web/
